"""
sft/sft_train.py
================
Supervised Fine-Tuning (SFT) baseline for SWE-RL re-implementation.

Trains Llama 3.1 8B on the synthetic CoT dataset generated by
generate_cot_data.py using standard cross-entropy loss (next-token prediction).

The SFT model serves as a comparison point:
  SFT baseline vs. SWE-RL (GRPO) baseline vs. base Llama 3.1 8B

Training config:
    - Steps    : 2,000
    - Batch    : 16 per device × grad_accum 8 = effective batch 128
    - LR       : 2e-5 (higher than RL since no reward noise)
    - Scheduler: cosine with 50 warmup steps

Usage:
    python -m sft.sft_train --config configs/train_config.yaml
"""

import argparse
import inspect
import logging
from pathlib import Path

import torch
from datasets import Dataset as HFDataset
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    DataCollatorForSeq2Seq,
    TrainingArguments,
    Trainer,
)

from agent.prompts import build_messages
from utils.io_utils import read_jsonl, read_yaml

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")


def enable_gradient_checkpointing_for_lora(model) -> None:
    """
    Keep the computation graph connected when gradient checkpointing is used
    with LoRA adapters on a frozen base model.
    """
    if hasattr(model, "enable_input_require_grads"):
        model.enable_input_require_grads()
        return

    input_embeddings = model.get_input_embeddings()

    def make_inputs_require_grad(_module, _inputs, output):
        output.requires_grad_(True)

    input_embeddings.register_forward_hook(make_inputs_require_grad)


def gradient_checkpointing_kwargs() -> dict:
    return {"use_reentrant": False}


def enable_model_gradient_checkpointing(model) -> None:
    if not hasattr(model, "gradient_checkpointing_enable"):
        return

    try:
        model.gradient_checkpointing_enable(
            gradient_checkpointing_kwargs=gradient_checkpointing_kwargs()
        )
    except TypeError:
        model.gradient_checkpointing_enable()


def validate_config(cfg: dict, config_path: str) -> None:
    if "model" not in cfg:
        raise ValueError(f"SFT config {config_path} missing model section")
    sft_cfg = cfg.get("sft_baseline", {})
    train_file = Path(sft_cfg.get("train_file", "data/processed/sft_cot_data.jsonl"))
    if not train_file.exists():
        raise FileNotFoundError(
            f"SFT data not found: {train_file}. Run `python run.py sft_data --config {config_path}` first."
        )
    if sft_cfg.get("max_steps", 0) <= 0:
        raise ValueError("sft_baseline.max_steps must be positive")
    if sft_cfg.get("per_device_train_batch_size", 0) <= 0:
        raise ValueError("sft_baseline.per_device_train_batch_size must be positive")


def load_sft_dataset(
    jsonl_file: str,
    tokenizer,
    max_length: int = 16384,
) -> HFDataset:
    """
    Load synthetic CoT data and tokenize for causal language modelling.

    Each example is formatted as:
        [SYSTEM]\n{thinking_system}\n[USER]\n{repair_prompt}\n[ASSISTANT]\n{output}

    We mask the loss on the prompt tokens so the model only learns to
    produce the chain-of-thought + solution.
    """
    records = read_jsonl(jsonl_file)

    logger.info(f"Loaded {len(records)} SFT records from {jsonl_file}")

    def tokenize(example: dict):
        problem_statement = example.get("problem_statement", "")
        code_context = example.get("code_context", "")
        output = example.get("output", "")

        messages = build_messages(problem_statement, code_context)
        prompt_str = tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True,
        )
        full_str = prompt_str + output + tokenizer.eos_token

        full_enc = tokenizer(
            full_str,
            max_length=max_length,
            truncation=True,
            return_tensors=None,
        )
        prompt_enc = tokenizer(
            prompt_str,
            max_length=max_length,
            truncation=True,
            return_tensors=None,
        )

        input_ids = full_enc["input_ids"]
        prompt_len = len(prompt_enc["input_ids"])

        # Mask loss on prompt tokens (labels = -100 for prompt, token id for response)
        labels = [-100] * prompt_len + input_ids[prompt_len:]

        return {
            "input_ids": input_ids,
            "attention_mask": full_enc["attention_mask"],
            "labels": labels,
        }

    hf_data = HFDataset.from_list(records)
    tokenized = hf_data.map(
        tokenize,
        remove_columns=hf_data.column_names,
        desc="Tokenizing SFT data",
    )
    return tokenized


def train_sft(config_path: str):
    cfg = read_yaml(config_path)
    validate_config(cfg, config_path)

    sft_cfg = cfg.get("sft_baseline", {})
    model_cfg = cfg["model"]
    log_cfg = cfg.get("logging", {})

    model_name = model_cfg["name_or_path"]
    output_dir = sft_cfg.get("output_dir", "outputs/sft")
    train_file = sft_cfg.get("train_file", "data/processed/sft_cot_data.jsonl")
    max_length = sft_cfg.get("max_length", 16384)
    dtype_map = {"bfloat16": torch.bfloat16, "float16": torch.float16, "float32": torch.float32}
    requested_dtype_name = model_cfg.get("torch_dtype", "float16")
    torch_dtype = dtype_map.get(requested_dtype_name, torch.float16)

    # fp16 weights without AMP/grad scaling overflow on the first non-trivial
    # cross-entropy loss (we observed step-1 loss=80 → grads blow past fp16's
    # ~65504 dynamic range → all LoRA params NaN → rest of training dead).
    # When the user requested fp16 on a non-quantized model, silently upgrade
    # to fp32 — same fallback the GRPO side already uses. bf16 is preserved
    # if explicitly requested and supported by the GPU.
    if (
        torch_dtype is torch.float16
        and not model_cfg.get("load_in_4bit", False)
        and not sft_cfg.get("force_model_dtype", False)
    ):
        logger.info(
            "Upgrading requested fp16 to fp32 for non-quantized SFT (avoids "
            "fp16 gradient overflow on small LoRA models). "
            "Set sft_baseline.force_model_dtype=true to override."
        )
        torch_dtype = torch.float32
    effective_dtype_name = {
        torch.float16: "float16",
        torch.bfloat16: "bfloat16",
        torch.float32: "float32",
    }.get(torch_dtype, str(torch_dtype))

    use_bf16 = (
        torch_dtype is torch.bfloat16
        and torch.cuda.is_available()
        and torch.cuda.is_bf16_supported()
    )
    # Only enable fp16 AMP when the user explicitly forced an fp16 model AND
    # has a CUDA device. Without that combination we keep AMP off so the
    # default fp32 path is the simple, stable one.
    use_fp16 = (
        torch_dtype is torch.float16
        and torch.cuda.is_available()
    )
    logger.info(
        "SFT config: model=%s train_file=%s output_dir=%s max_length=%s",
        model_name,
        train_file,
        output_dir,
        max_length,
    )
    logger.info(
        "SFT dtype: requested=%s effective=%s bf16_amp=%s fp16_amp=%s cuda=%s",
        requested_dtype_name,
        effective_dtype_name,
        use_bf16,
        use_fp16,
        torch.cuda.is_available(),
    )

    logger.info(f"Loading tokenizer: {model_name}")
    tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "right"
    tokenizer.model_max_length = max_length

    train_dataset = load_sft_dataset(train_file, tokenizer, max_length=max_length)

    logger.info(f"Loading model: {model_name}")
    quant_config = None
    if model_cfg.get("load_in_4bit", False):
        quant_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_compute_dtype=torch_dtype,
            bnb_4bit_use_double_quant=True,
            bnb_4bit_quant_type="nf4",
        )

    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        torch_dtype=torch_dtype,
        quantization_config=quant_config,
        device_map="auto",
        trust_remote_code=True,
    )

    # If the tokenizer ended up with more tokens than the model's embedding
    # rows (common when special tokens like <think>, <solution> are added by
    # the chat template), resize so the model can predict them. Without this,
    # the model's logits over the new IDs are random/uninitialized, which
    # produces the absurdly high step-1 cross-entropy loss we saw.
    embedding_rows = model.get_input_embeddings().weight.shape[0]
    if len(tokenizer) > embedding_rows:
        logger.info(
            "Resizing token embeddings: %d -> %d to cover added special tokens",
            embedding_rows,
            len(tokenizer),
        )
        model.resize_token_embeddings(len(tokenizer))

    # LoRA for SFT (same config as GRPO for fair comparison)
    if model_cfg.get("load_in_4bit", False):
        model = prepare_model_for_kbit_training(
            model,
            use_gradient_checkpointing=True,
        )

    lora_cfg = model_cfg.get("lora", {})
    lora_config = LoraConfig(
        r=lora_cfg.get("r", 64),
        lora_alpha=lora_cfg.get("lora_alpha", 128),
        target_modules=lora_cfg.get("target_modules", ["q_proj", "v_proj", "k_proj", "o_proj"]),
        lora_dropout=lora_cfg.get("lora_dropout", 0.05),
        bias="none",
        task_type="CAUSAL_LM",
    )
    model = get_peft_model(model, lora_config)
    model.print_trainable_parameters()
    model.config.use_cache = False

    enable_gradient_checkpointing_for_lora(model)
    enable_model_gradient_checkpointing(model)

    # Ensure model is in training mode
    model.train()

    # AMP wiring: use bf16 AMP when the user has explicitly asked for bf16
    # weights and the GPU supports it. Otherwise stay in fp32 — fp16 AMP
    # with frozen base + LoRA is technically valid but has caused the
    # gradient-scaler conflicts that the original code was trying to avoid.
    training_args_kwargs = {
        "output_dir": output_dir,
        "max_steps": sft_cfg.get("max_steps", 2000),
        "per_device_train_batch_size": sft_cfg.get("per_device_train_batch_size", 2),
        "gradient_accumulation_steps": sft_cfg.get("gradient_accumulation_steps", 8),
        "learning_rate": sft_cfg.get("learning_rate", 2e-5),
        "lr_scheduler_type": sft_cfg.get("lr_scheduler", "cosine"),
        "warmup_steps": sft_cfg.get("warmup_steps", 50),
        "bf16": use_bf16,
        "fp16": False,  # We never enable fp16 AMP automatically; opt-in only.
        "max_grad_norm": sft_cfg.get("max_grad_norm", 1.0),
        "gradient_checkpointing": True,
        "save_steps": 200,
        "logging_steps": 10,
        "report_to": log_cfg.get("report_to", "none"),
        "run_name": log_cfg.get("wandb_run_name", "sft-baseline") + "-sft",
        "remove_unused_columns": False,
        "dataloader_num_workers": 0,
    }
    if "gradient_checkpointing_kwargs" in inspect.signature(TrainingArguments).parameters:
        training_args_kwargs["gradient_checkpointing_kwargs"] = gradient_checkpointing_kwargs()

    training_args = TrainingArguments(**training_args_kwargs)

    data_collator = DataCollatorForSeq2Seq(
        tokenizer=tokenizer,
        model=model,
        label_pad_token_id=-100,
        pad_to_multiple_of=8,
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        data_collator=data_collator,
    )

    logger.info("Starting SFT training...")
    trainer.train()

    # Save
    final_dir = Path(output_dir) / "final"
    logger.info(f"Saving SFT model to {final_dir}")
    trainer.save_model(str(final_dir))
    tokenizer.save_pretrained(str(final_dir))
    logger.info("SFT training complete.")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", default="configs/train_config.yaml")
    args = parser.parse_args()
    train_sft(config_path=args.config)


if __name__ == "__main__":
    main()
